# 15) Escreva um programa que imprima na tela para escrever a tabuada de um número fornecido pelo usuário, de 1 a 10.
from time import sleep


num = int(input('Insira um número de 01 a 10 para calcular a sua tabuada: '))

while num > 10 or num < 1:
    num = int(input('Insira um número de 01 a 10 para calcular a sua tabuada: '))

print('[1]DIVISÃO\n[2]MULTIPLICAÇÃO\n[3]SUBTRAÇÃO\n[4]ADIÇÃO\n[5]SAIR')
operacao = int(input('Insira a sua opção de operação: '))

while operacao >= 1 and operacao <= 5:
    if operacao == 1:
        print('-'*50)
        print('DIVISÃO')
        print('-'*50)
        print(f'{num} / {1: 2} = {num/1: .2f}')
        print(f'{num} / {2: 2} = {num/2: .2f}')
        print(f'{num} / {3: 2} = {num/3: .2f}')
        print(f'{num} / {4: 2} = {num/4: .2f}')
        print(f'{num} / {5: 2} = {num/5: .2f}')
        print(f'{num} / {6: 2} = {num/6: .2f}')
        print(f'{num} / {7: 2} = {num/7: .2f}')
        print(f'{num} / {8: 2} = {num/8: .2f}')
        print(f'{num} / {9: 2} = {num/9: .2f}')
        print(f'{num} / {10} = {num/10: .2f}')
        exit()
    elif operacao == 2:
        print('-'*50)
        print('MULTIPLICAÇÃO')
        print('-'*5)
        print(f'{num} X {1: 2} = {num*1}')
        print(f'{num} X {2: 2} = {num*2}')
        print(f'{num} X {3: 2} = {num*3}')
        print(f'{num} X {4: 2} = {num*4}')
        print(f'{num} X {5: 2} = {num*5}')
        print(f'{num} X {6: 2} = {num*6}')
        print(f'{num} X {7: 2} = {num*7}')
        print(f'{num} X {8: 2} = {num*8}')
        print(f'{num} X {9: 2} = {num*9}')
        print(f'{num} X {10} = {num*10}')
        exit()
    elif operacao == 3:
        print('-'*50)
        print('SUBTRAÇÃO')
        print('-'*5)
        print(f'{num} - {1: 2} = {num-1}')
        print(f'{num} - {2: 2} = {num-2}')
        print(f'{num} - {3: 2} = {num-3}')
        print(f'{num} - {4: 2} = {num-4}')
        print(f'{num} - {5: 2} = {num-5}')
        print(f'{num} - {6: 2} = {num-6}')
        print(f'{num} - {7: 2} = {num-7}')
        print(f'{num} - {8: 2} = {num-8}')
        print(f'{num} - {9: 2} = {num-9}')
        print(f'{num} - {10} = {num-10}')
        exit()
    elif operacao == 4:
        print('-'*50)
        print('ADIÇÃO')
        print('-'*5)
        print(f'{num} + {1: 2} = {num+1}')
        print(f'{num} + {2: 2} = {num+2}')
        print(f'{num} + {3: 2} = {num+3}')
        print(f'{num} + {4: 2} = {num+4}')
        print(f'{num} + {5: 2} = {num+5}')
        print(f'{num} + {6: 2} = {num+6}')
        print(f'{num} + {7: 2} = {num+7}')
        print(f'{num} + {8: 2} = {num+8}')
        print(f'{num} + {9: 2} = {num+9}')
        print(f'{num} + {10} = {num+10}')
        exit()
    else:
        print('Você escolheu sair do programa!')
        sleep(.8)
        print('.'*31)
        sleep(.8)
        print('Você escolheu sair do programa!')
        sleep(.8)
        print('.'*31)
        sleep(.8)
        print('Você escolheu sair do programa!')
        exit()
